### ISSUE TITLE
Bug: 2025/mattprep does not build on NetBSD 10.1

### ISSUE THREAD

**Issue by SirWumpus** [ioccc-src/winner#275]
### Is there an existing issue for this?

- [x] I have searched for existing issues and did not find anything like this

### Describe the bug

Trying to build 2025/mattprep.  It appears how `getchar()` is used, while clever, is not portable.  The NetBSD definition of `getchar` does not define an argument and `gcc 14.3.0` complains.

```
cc -std=gnu17 -Wall -Wextra -pedantic -Wno-poison-system-directories -Wno-unused-value -Wno-type-limits -Wno-char-subscripts -Wno-misleading-indentation -Wno-strict-prototypes -Wno-unicode-homoglyph -Wno-unknown-warning-option  -Ugetchar -D'getchar(x)=getc(stdin)'   -O3 prog.c -o prog 
In file included from prog.c:1:
<command-line>: error: expected declaration specifiers or '...' before '(' token
prog.c: In function 'main':
prog.c:65:38: error: macro "getchar" passed 1 arguments, but takes just 0
   65 |     while ((N = getchar( B == А[!i^i]) C *В++ = N; *Х = '='; four--
      |                                      ^
/usr/pkg/gcc14/lib/gcc/x86_64--netbsd/14.3.0/include-fixed/stdio.h:512:9: note: macro "getchar" defined here
  512 | #define getchar()       getc(stdin)
      |         ^~~~~~~
prog.c:65:17: error: 'getchar' undeclared (first use in this function)
   65 |     while ((N = getchar( B == А[!i^i]) C *В++ = N; *Х = '='; four--
      |                 ^~~~~~~
prog.c:3:1: note: 'getchar' is defined in header '<stdio.h>'; this is probably fixable by adding '#include <stdio.h>'
    2 | #include <unistd.h>
  +++ |+#include <stdio.h>
    3 | 
prog.c:65:17: note: each undeclared identifier is reported only once for each function it appears in
   65 |     while ((N = getchar( B == А[!i^i]) C *В++ = N; *Х = '='; four--
      |                 ^~~~~~~
prog.c:65:24: error: expected ')' before ';' token
   65 |     while ((N = getchar( B == А[!i^i]) C *В++ = N; *Х = '='; four--
      |            ~           ^
      |                        )
prog.c:66:39: error: expected ')' before '}' token
   66 |     &&main((б4+б4)/б4/64,A); return 0; } if(a==(б4+б4)/б4/64){ if(Ε
      |                                       ^~
      |                                       )
prog.c:65:11: note: to match this '('
   65 |     while ((N = getchar( B == А[!i^i]) C *В++ = N; *Х = '='; four--
      |           ^
prog.c:66:40: error: expected expression before '}' token
   66 |     &&main((б4+б4)/б4/64,A); return 0; } if(a==(б4+б4)/б4/64){ if(Ε
      |                                        ^
prog.c:87:9: error: macro "getchar" passed 1 arguments, but takes just 0
   87 |     '\n'); if(N==D)
      |         ^
/usr/pkg/gcc14/lib/gcc/x86_64--netbsd/14.3.0/include-fixed/stdio.h:512:9: note: macro "getchar" defined here
  512 | #define getchar()       getc(stdin)
      |         ^~~~~~~
prog.c:86:65: error: expected ')' before ';' token
   86 |     ){ four=4; ｛=А[1]>>((б4+б4)/б4/64); В=O; } while((N=getchar(B==
      |                                                       ~         ^
      |                                                                 )
   87 |     '\n'); if(N==D)
      |          ~                                                       
prog.c:93:46: error: expected ')' before '}' token
   93 |     =Ε; } Е=1,Ε=0; main(a=(б4+б4)/б4/64,A); } } } Е && Ε && main(a=3,A); }
      |                                              ^~
      |                                              )
prog.c:86:54: note: to match this '('
   86 |     ){ four=4; ｛=А[1]>>((б4+б4)/б4/64); В=O; } while((N=getchar(B==
      |                                                      ^
prog.c:93:47: error: expected expression before '}' token
   93 |     =Ε; } Е=1,Ε=0; main(a=(б4+б4)/б4/64,A); } } } Е && Ε && main(a=3,A); }
      |                                               ^
At top level:
cc1: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option '-Wno-unicode-homoglyph' may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option '-Wno-poison-system-directories' may have been intended to silence earlier diagnostics
gmake: *** [Makefile:164: prog] Error 1
```

The work around would be to add after stdio.h:
```
#undef getchar
#define getchar(x) getc(stdin)
```
But that would void the iocccsize constraint.  I've tried to handle this using Makefile `CDEFINES` something like `CDEFINES= -Ugetchar -D'getchar(x)=getc(stdin)', but that doesn't appear to work either (yet supported by gcc).

### What you expect

Winning the lottery.

### Environment

- OS: NetBSD 10.1 VM
- Device:
- Compiler: gcc 14.3.0

**Comment by lcn2** [comment]
Just to clarify the bug title, does it to doesn't build under NetBSD 10.1?

**Comment by SirWumpus** [comment]
Fixed

**Comment by lcn2** [comment]
We will look at a solution for NetBSD 10.1 along the lines you suggest.

**Comment by lcn2** [comment]
Thank you @SirWumpus L we have addressed this issue with commit 58c77c66a448baf0dab2363426b407e265b270ee
